services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file: .env
    restart: always
    ports:
        - '5432:5432'
    volumes:
      - postgres-vol:/var/lib/postgresql
  
  postgres_test:
    image: postgres:16-alpine
    container_name: postgres_test
    env_file: .env.test
    restart: always
    ports:
        - '5433:5433'

volumes:  
  postgres-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/guribeir/postgres_data'